import { supabase } from '../lib/supabase'
import type { Category,IcePriceTier,Product } from '../types/database'
import { cachedQuery,invalidateQuery } from '../lib/queryCache'
export async function listCategories(activeOnly=true){return cachedQuery(`categories:${activeOnly}`,async()=>{let query=supabase.from('categories').select('*').order('sort_order');if(activeOnly)query=query.eq('is_active',true);const {data,error}=await query;if(error)throw error;return data as Category[]})}
export async function listProducts(includeArchived=false){return cachedQuery(`products:${includeArchived}`,async()=>{let query=supabase.from('products').select('*, category:categories(name,slug)').order('name');if(!includeArchived)query=query.eq('is_active',true);const {data,error}=await query;if(error)throw error;return data as Product[]})}
export async function getProduct(id:string){return cachedQuery(`product:${id}`,async()=>{const {data,error}=await supabase.from('products').select('*').eq('id',id).single();if(error)throw error;return data as Product})}
export async function listIceTiers(){return cachedQuery('ice-tiers',async()=>{const {data,error}=await supabase.from('ice_price_tiers').select('*').eq('is_active',true).order('min_kg');if(error)throw error;return data as IcePriceTier[]})}
export async function saveIceTier(input:{min_kg:number;max_kg:number;price_per_kg_centavos:number}){const {error}=await supabase.from('ice_price_tiers').insert(input);if(error)throw error;invalidateQuery('ice-tiers')}
export async function updateIceTier(id:string,input:{min_kg:number;max_kg:number;price_per_kg_centavos:number}){const {error}=await supabase.from('ice_price_tiers').update(input).eq('id',id);if(error)throw error;invalidateQuery('ice-tiers')}
export async function deleteIceTier(id:string){const {error}=await supabase.from('ice_price_tiers').delete().eq('id',id);if(error)throw error;invalidateQuery('ice-tiers')}
export type ProductInput=Pick<Product,'name'|'category_id'|'description'|'price_centavos'|'unit_type'|'is_available'|'track_stock'|'stock_quantity'>
export async function saveProduct(input:ProductInput,id?:string){const payload={...input,updated_at:new Date().toISOString()};const result=id?await supabase.from('products').update(payload).eq('id',id).select().single():await supabase.from('products').insert(payload).select().single();if(result.error)throw result.error;invalidateQuery('products');if(id)invalidateQuery(`product:${id}`);return result.data as Product}
export async function deleteProduct(id:string){const {data:imagePath,error}=await supabase.rpc('delete_product_permanently',{p_product_id:id});if(error)throw error;if(imagePath)await supabase.storage.from('product-images').remove([imagePath]);invalidateQuery('products');invalidateQuery(`product:${id}`)}
export async function setAvailability(id:string,is_available:boolean){const {error}=await supabase.from('products').update({is_available,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;invalidateQuery('products');invalidateQuery(`product:${id}`)}
export async function uploadProductImage(productId:string,categorySlug:string,file:File,oldPath:string|null){const ext=file.type==='image/jpeg'?'jpg':file.type==='image/png'?'png':'webp';const path=`${categorySlug}/${crypto.randomUUID()}.${ext}`;const {error:uploadError}=await supabase.storage.from('product-images').upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const {error:updateError}=await supabase.from('products').update({image_path:path,updated_at:new Date().toISOString()}).eq('id',productId);if(updateError){await supabase.storage.from('product-images').remove([path]);throw updateError}if(oldPath){const {count}=await supabase.from('products').select('*',{count:'exact',head:true}).eq('image_path',oldPath);if(count===0)await supabase.storage.from('product-images').remove([oldPath])}invalidateQuery('products');invalidateQuery(`product:${productId}`);return path}
export function productImageUrl(path:string|null){if(!path)return null;return supabase.storage.from('product-images').getPublicUrl(path).data.publicUrl}
