import { useCallback,useRef,useState } from 'react'
import { Navigate,useLocation,useNavigate } from 'react-router-dom'
import { Coffee,LoaderCircle } from 'lucide-react'
import { z } from 'zod'
import { AutoFaceCamera } from '../components/auth/AutoFaceCamera'
import { supabase } from '../lib/supabase'
import { useAuth } from '../features/auth/AuthProvider'
import { startAttendance,verifyFace } from '../services/staff'
import { usernameToAuthEmail } from '../utils/auth'

const schema=z.object({username:z.string().trim().min(3,'Enter a valid username.'),password:z.string().min(8,'Password must be at least 8 characters.')})
export function LoginPage(){
  const {session}=useAuth();const navigate=useNavigate();const location=useLocation();const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [recovery,setRecovery]=useState(false);const [loginToken,setLoginToken]=useState('');const [matchedName,setMatchedName]=useState('');const faceScanningEnabled=useRef(true)
  function finishNavigation(){const from=(location.state as {from?:{pathname?:string}})?.from?.pathname;navigate(from||'/pos',{replace:true})}
  const scanFace=useCallback(async(image:Blob)=>{try{const result=await verifyFace(image);if(!faceScanningEnabled.current)return;setError('');setMatchedName(result.full_name);setLoginToken(result.token_hash)}catch(cause){if(!faceScanningEnabled.current)return;const message=cause instanceof Error?cause.message:'';if(message.includes('not recognized'))setError('Face mismatch. No registered staff account matches this face.');else if(message.includes('Too many'))setError(message)}},[])
  if(session)return <Navigate to="/pos" replace/>
  async function confirmFaceLogin(){if(!loginToken)return;setLoading(true);setError('');try{const {error:authError}=await supabase.auth.verifyOtp({token_hash:loginToken,type:'magiclink'});if(authError)throw authError;await startAttendance('FACE');await supabase.rpc('log_auth_event',{p_action:'LOGIN'});finishNavigation()}catch(cause){setLoginToken('');setError(cause instanceof Error?cause.message:'Face login failed. Please scan again.')}finally{setLoading(false)}}
  async function ownerLogin(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');const form=new FormData(e.currentTarget);const parsed=schema.safeParse({username:form.get('username'),password:form.get('password')});if(!parsed.success){setError(parsed.error.issues[0].message);return}let email:string;try{email=usernameToAuthEmail(parsed.data.username)}catch(cause){setError(cause instanceof Error?cause.message:'Enter a valid username.');return}setLoading(true);try{const {data,error:authError}=await supabase.auth.signInWithPassword({email,password:parsed.data.password});if(authError||!data.user)throw new Error('Incorrect owner username or password.');const {data:profile}=await supabase.from('profiles').select('role').eq('id',data.user.id).single();if(profile?.role!=='OWNER'){await supabase.auth.signOut();throw new Error('Password recovery is available to owners only.')}await supabase.rpc('log_auth_event',{p_action:'LOGIN'});finishNavigation()}catch(cause){setError(cause instanceof Error?cause.message:'Owner login failed.')}finally{setLoading(false)}}
  return <main className="grid min-h-screen place-items-center bg-brand-900 p-5"><section className="w-full max-w-md rounded-3xl bg-white p-8 shadow-2xl"><div className="mb-6 text-center"><Coffee className="mx-auto mb-3 text-brand-500" size={44}/><h1 className="text-2xl font-bold">CUP LAB</h1><p className="mt-1 text-sm text-stone-500">Staff face verification</p></div>
    {!recovery?<><AutoFaceCamera onScan={scanFace} paused={Boolean(loginToken)||loading} pausedLabel={matchedName||'Verifying...'}/>{error&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button onClick={()=>{faceScanningEnabled.current=false;setRecovery(true);setError('');setLoginToken('');setMatchedName('')}} className="mt-5 flex w-full items-center justify-center text-sm font-semibold text-stone-500">Admin log in</button></>
    :<form onSubmit={ownerLogin}><label className="mb-4 block text-sm font-semibold">Owner username<input name="username" autoComplete="username" required className="mt-1.5 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="mb-5 block text-sm font-semibold">Password<input name="password" type="password" autoComplete="current-password" required className="mt-1.5 w-full rounded-xl border px-4 py-3 font-normal"/></label>{error&&<p role="alert" className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-xl bg-brand-500 py-3 font-bold text-white disabled:opacity-60">{loading&&<LoaderCircle className="animate-spin" size={18}/>} {loading?'Logging in...':'Log in'}</button><button type="button" onClick={()=>{faceScanningEnabled.current=true;setRecovery(false);setError('')}} className="mt-4 w-full text-sm font-semibold text-stone-500">Staff log in</button></form>}
  </section>{loginToken&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4" role="dialog" aria-modal="true" aria-labelledby="login-title"><section className="w-full max-w-sm rounded-2xl bg-white p-6 shadow-2xl"><h2 id="login-title" className="text-xl font-bold">{matchedName}</h2><p className="mt-2 text-sm text-stone-600">Do you want to log in and start your duty session?</p><div className="mt-6 flex gap-3"><button onClick={()=>{setLoginToken('');setMatchedName('')}} disabled={loading} className="flex-1 rounded-xl border py-3 font-semibold">Cancel</button><button onClick={()=>void confirmFaceLogin()} disabled={loading} className="flex-1 rounded-xl bg-brand-500 py-3 font-bold text-white disabled:opacity-50">{loading?'Logging in...':'Log in'}</button></div></section></div>}</main>
}
