import { useCallback,useEffect,useMemo,useState } from 'react'
import { Edit,Trash2,UserPlus } from 'lucide-react'
import { deleteStaff,listAttendance,listStaff,registerStaff,updateStaff } from '../services/staff'
import type { AttendanceSession,Profile } from '../types/database'

function duration(session:AttendanceSession){const end=session.clocked_out_at?new Date(session.clocked_out_at).getTime():Date.now();const minutes=Math.max(0,Math.floor((end-new Date(session.clocked_in_at).getTime())/60000));return `${Math.floor(minutes/60)}h ${minutes%60}m`}

export function StaffPage(){
  const [staff,setStaff]=useState<Profile[]>([]);const [attendance,setAttendance]=useState<AttendanceSession[]>([])
  const [selectedMonth,setSelectedMonth]=useState(()=>{const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`})
  const [showForm,setShowForm]=useState(false);const [fullName,setFullName]=useState('');const [username,setUsername]=useState('');const [contactEmail,setContactEmail]=useState('');const [password,setPassword]=useState('');const [saving,setSaving]=useState(false);const [message,setMessage]=useState<{error?:string;success?:string}>({})
  const [editing,setEditing]=useState<Profile|null>(null);const [editName,setEditName]=useState('');const [editUsername,setEditUsername]=useState('');const [editContactEmail,setEditContactEmail]=useState('');const [editPassword,setEditPassword]=useState('');const [deletingId,setDeletingId]=useState<string|null>(null)
  const load=useCallback(async()=>{try{const [people,sessions]=await Promise.all([listStaff(),listAttendance()]);setStaff(people);setAttendance(sessions);setMessage({})}catch{setMessage({error:'Unable to load staff. Owner access is required.'})}},[])
  useEffect(()=>{void load()},[load])
  const monthRange=useMemo(()=>{const [year,month]=selectedMonth.split('-').map(Number);return {start:new Date(year,month-1,1).getTime(),end:new Date(year,month,1).getTime()}},[selectedMonth])
  const filteredAttendance=useMemo(()=>attendance.filter(item=>new Date(item.clocked_in_at).getTime()<monthRange.end&&new Date(item.clocked_out_at??Date.now()).getTime()>=monthRange.start),[attendance,monthRange])
  const totals=useMemo(()=>new Map(staff.map(person=>[person.id,filteredAttendance.filter(item=>item.staff_id===person.id).reduce((sum,item)=>{const start=Math.max(new Date(item.clocked_in_at).getTime(),monthRange.start);const end=Math.min(new Date(item.clocked_out_at??Date.now()).getTime(),monthRange.end);return sum+Math.max(0,end-start)},0)])),[staff,filteredAttendance,monthRange])

  async function enroll(event:React.FormEvent){event.preventDefault();setSaving(true);setMessage({});try{await registerStaff(fullName.trim(),username.trim().toLowerCase(),contactEmail.trim().toLowerCase(),password);setMessage({success:'Staff account created. They can now log in with the assigned username and password.'});setFullName('');setUsername('');setContactEmail('');setPassword('');setShowForm(false);await load()}catch(error){setMessage({error:error instanceof Error?error.message:'Unable to register staff.'})}finally{setSaving(false)}}
  function openEdit(person:Profile){setEditing(person);setEditName(person.full_name);setEditUsername(person.username);setEditContactEmail(person.contact_email??'');setEditPassword('');setMessage({})}
  async function saveEdit(event:React.FormEvent){event.preventDefault();if(!editing)return;setSaving(true);try{await updateStaff(editing.id,editName.trim(),editUsername.trim().toLowerCase(),editContactEmail.trim().toLowerCase(),editPassword||undefined);setEditing(null);setMessage({success:'Staff account updated.'});await load()}catch(error){setMessage({error:error instanceof Error?error.message:'Unable to update staff.'})}finally{setSaving(false)}}
  async function remove(person:Profile){setDeletingId(person.id);setMessage({});try{await deleteStaff(person.id);setStaff(current=>current.filter(item=>item.id!==person.id));setMessage({success:'Staff account deleted.'})}catch(error){setMessage({error:error instanceof Error?error.message:'Unable to delete staff.'})}finally{setDeletingId(null)}}

  return <div className="p-4 pt-16 lg:p-8"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-bold">Staff & Attendance</h1><p className="text-sm text-stone-500">Create staff login credentials and monitor accumulated duty hours.</p></div><button onClick={()=>setShowForm(value=>!value)} className="flex items-center gap-2 rounded-xl bg-brand-500 px-4 py-3 font-bold text-white"><UserPlus size={18}/>Register staff</button></div>
    {message.error&&<p role="alert" className="mb-4 rounded-xl bg-red-50 p-3 text-red-700">{message.error}</p>}{message.success&&<p className="mb-4 rounded-xl bg-emerald-50 p-3 text-emerald-700">{message.success}</p>}
    {showForm&&<form onSubmit={enroll} className="mb-6 max-w-xl rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">New staff member</h2><p className="mb-5 text-sm text-stone-500">Create login credentials and save a separate contact email.</p><label className="mb-4 block text-sm font-semibold">Full name<input value={fullName} onChange={event=>setFullName(event.target.value)} required className="mt-1.5 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="mb-4 block text-sm font-semibold">Username<input value={username} onChange={event=>setUsername(event.target.value)} pattern="[a-z0-9._\-]{3,32}" required className="mt-1.5 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="mb-4 block text-sm font-semibold">Contact email<input value={contactEmail} onChange={event=>setContactEmail(event.target.value)} type="email" autoComplete="email" required className="mt-1.5 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="block text-sm font-semibold">Password<input value={password} onChange={event=>setPassword(event.target.value)} type="password" minLength={8} autoComplete="new-password" required className="mt-1.5 w-full rounded-xl border px-4 py-3 font-normal"/></label><p className="mt-2 text-xs text-stone-500">Staff will still sign in with the username, not this email.</p><button disabled={saving} className="mt-5 w-full rounded-xl bg-brand-500 py-3 font-bold text-white disabled:opacity-50">{saving?'Creating...':'Create staff account'}</button></form>}
    <section className="rounded-2xl bg-white shadow-sm"><div className="flex flex-wrap items-end justify-between gap-3 p-4"><div><h2 className="font-bold">Accumulated hours</h2><p className="text-sm text-stone-500">Duty time within the selected month.</p></div><label className="text-sm font-semibold">Month<input type="month" value={selectedMonth} onChange={event=>setSelectedMonth(event.target.value)} className="ml-2 rounded-lg border px-3 py-2 font-normal"/></label></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left"><thead className="border-y bg-stone-50 text-xs uppercase text-stone-500"><tr><th className="p-4">Staff</th><th>Username</th><th>Contact email</th><th>Status</th><th>Current duty</th><th>Accumulated hours</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{staff.map(person=>{const open=attendance.find(item=>item.staff_id===person.id&&!item.clocked_out_at);const totalMinutes=Math.floor((totals.get(person.id)??0)/60000);return <tr key={person.id} className="border-b last:border-0"><td className="p-4 font-semibold">{person.full_name}</td><td>{person.username}</td><td>{person.contact_email??'—'}</td><td>Active</td><td>{open?duration(open):'Off duty'}</td><td className="font-bold">{Math.floor(totalMinutes/60)}h {totalMinutes%60}m</td><td className="p-4"><div className="flex justify-end gap-2"><button onClick={()=>openEdit(person)} className="rounded-lg border p-2 text-brand-600" aria-label={`Edit ${person.full_name}`}><Edit size={17}/></button><button onClick={()=>void remove(person)} disabled={deletingId===person.id} className="rounded-lg border border-red-200 p-2 text-red-600 disabled:opacity-50" aria-label={`Delete ${person.full_name}`}><Trash2 size={17}/></button></div></td></tr>})}</tbody></table></div></section>
    <section className="mt-6 overflow-x-auto rounded-2xl bg-white shadow-sm"><h2 className="p-4 text-lg font-bold">Attendance history</h2><table className="w-full min-w-[760px] text-left"><thead className="border-y bg-stone-50 text-xs uppercase text-stone-500"><tr><th className="p-4">Staff</th><th>Clock in</th><th>Clock out</th><th>Method</th><th className="p-4">Duty time</th></tr></thead><tbody>{filteredAttendance.map(item=><tr key={item.id} className="border-b last:border-0"><td className="p-4 font-semibold">{item.profiles?.full_name??'Staff'}</td><td>{new Date(item.clocked_in_at).toLocaleString()}</td><td>{item.clocked_out_at?new Date(item.clocked_out_at).toLocaleString():'On duty'}</td><td>Password</td><td className="p-4">{duration(item)}</td></tr>)}{filteredAttendance.length===0&&<tr><td colSpan={5} className="p-10 text-center text-stone-500">No attendance records for this month.</td></tr>}</tbody></table></section>
    {editing&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4" role="dialog" aria-modal="true" aria-labelledby="edit-staff-title"><form onSubmit={saveEdit} className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h2 id="edit-staff-title" className="text-xl font-bold">Edit staff</h2><label className="mt-5 block text-sm font-semibold">Full name<input value={editName} onChange={event=>setEditName(event.target.value)} required className="mt-1.5 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="mt-4 block text-sm font-semibold">Username<input value={editUsername} onChange={event=>setEditUsername(event.target.value)} pattern="[a-z0-9._\-]{3,32}" required className="mt-1.5 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="mt-4 block text-sm font-semibold">Contact email<input value={editContactEmail} onChange={event=>setEditContactEmail(event.target.value)} type="email" autoComplete="email" required className="mt-1.5 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="mt-4 block text-sm font-semibold">New password <span className="font-normal text-stone-500">(optional)</span><input value={editPassword} onChange={event=>setEditPassword(event.target.value)} type="password" minLength={8} autoComplete="new-password" className="mt-1.5 w-full rounded-xl border px-4 py-3 font-normal"/></label><div className="mt-6 flex gap-3"><button type="button" onClick={()=>setEditing(null)} disabled={saving} className="flex-1 rounded-xl border py-3 font-semibold">Cancel</button><button disabled={saving} className="flex-1 rounded-xl bg-brand-500 py-3 font-bold text-white disabled:opacity-50">{saving?'Saving...':'Save'}</button></div></form></div>}
  </div>
}
