import { useCallback,useEffect,useMemo,useState } from 'react'
import { UserPlus } from 'lucide-react'
import { FaceCamera } from '../components/auth/FaceCamera'
import { listAttendance,listStaff,registerStaff } from '../services/staff'
import type { AttendanceSession,Profile } from '../types/database'

function duration(session:AttendanceSession){const end=session.clocked_out_at?new Date(session.clocked_out_at).getTime():Date.now();const minutes=Math.max(0,Math.floor((end-new Date(session.clocked_in_at).getTime())/60000));return `${Math.floor(minutes/60)}h ${minutes%60}m`}

export function StaffPage(){
  const [staff,setStaff]=useState<Profile[]>([]);const [attendance,setAttendance]=useState<AttendanceSession[]>([])
  const [selectedMonth,setSelectedMonth]=useState(()=>{const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`})
  const [showForm,setShowForm]=useState(false);const [fullName,setFullName]=useState('');const [username,setUsername]=useState('');const [saving,setSaving]=useState(false);const [message,setMessage]=useState<{error?:string;success?:string}>({})
  const load=useCallback(async()=>{try{const [people,sessions]=await Promise.all([listStaff(),listAttendance()]);setStaff(people);setAttendance(sessions);setMessage({})}catch{setMessage({error:'Unable to load staff. Owner access is required.'})}},[])
  useEffect(()=>{void load()},[load])
  const monthRange=useMemo(()=>{const [year,month]=selectedMonth.split('-').map(Number);return {start:new Date(year,month-1,1).getTime(),end:new Date(year,month,1).getTime()}},[selectedMonth])
  const filteredAttendance=useMemo(()=>attendance.filter(item=>new Date(item.clocked_in_at).getTime()<monthRange.end&&new Date(item.clocked_out_at??Date.now()).getTime()>=monthRange.start),[attendance,monthRange])
  const totals=useMemo(()=>new Map(staff.map(person=>[person.id,filteredAttendance.filter(item=>item.staff_id===person.id).reduce((sum,item)=>{const start=Math.max(new Date(item.clocked_in_at).getTime(),monthRange.start);const end=Math.min(new Date(item.clocked_out_at??Date.now()).getTime(),monthRange.end);return sum+Math.max(0,end-start)},0)])),[staff,filteredAttendance,monthRange])
  async function enroll(image:Blob){if(!fullName.trim()||!username.trim()){setMessage({error:'Enter the staff name and username first.'});return}setSaving(true);setMessage({});try{await registerStaff(fullName.trim(),username.trim().toLowerCase(),image);setMessage({success:'Staff member registered and face enrolled.'});setFullName('');setUsername('');setShowForm(false);await load()}catch(error){setMessage({error:error instanceof Error?error.message:'Unable to register staff.'})}finally{setSaving(false)}}
  return <div className="p-4 pt-16 lg:p-8"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-bold">Staff & Attendance</h1><p className="text-sm text-stone-500">Register staff faces and monitor accumulated duty hours.</p></div><button onClick={()=>setShowForm(value=>!value)} className="flex items-center gap-2 rounded-xl bg-brand-500 px-4 py-3 font-bold text-white"><UserPlus size={18}/>Register staff</button></div>
  {message.error&&<p role="alert" className="mb-4 rounded-xl bg-red-50 p-3 text-red-700">{message.error}</p>}{message.success&&<p className="mb-4 rounded-xl bg-emerald-50 p-3 text-emerald-700">{message.success}</p>}
  {showForm&&<section className="mb-6 grid max-w-4xl gap-6 rounded-2xl bg-white p-6 shadow-sm md:grid-cols-2"><div><h2 className="text-lg font-bold">New staff member</h2><p className="mb-5 text-sm text-stone-500">Enter details, then capture one clear live face.</p><label className="mb-4 block text-sm font-semibold">Full name<input value={fullName} onChange={e=>setFullName(e.target.value)} className="mt-1.5 w-full rounded-xl border px-4 py-3 font-normal"/></label><label className="block text-sm font-semibold">Username<input value={username} onChange={e=>setUsername(e.target.value)} pattern="[a-z0-9._\-]{3,32}" className="mt-1.5 w-full rounded-xl border px-4 py-3 font-normal"/></label></div><FaceCamera onCapture={image=>void enroll(image)} busy={saving} label="CAPTURE & REGISTER"/></section>}
  <section className="rounded-2xl bg-white shadow-sm"><div className="flex flex-wrap items-end justify-between gap-3 p-4"><div><h2 className="font-bold">Accumulated hours</h2><p className="text-sm text-stone-500">Duty time within the selected month.</p></div><label className="text-sm font-semibold">Month<input type="month" value={selectedMonth} onChange={event=>setSelectedMonth(event.target.value)} className="ml-2 rounded-lg border px-3 py-2 font-normal"/></label></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead className="border-y bg-stone-50 text-xs uppercase text-stone-500"><tr><th className="p-4">Staff</th><th>Role</th><th>Status</th><th>Current duty</th><th className="p-4">Accumulated hours</th></tr></thead><tbody>{staff.map(person=>{const open=attendance.find(item=>item.staff_id===person.id&&!item.clocked_out_at);const milliseconds=totals.get(person.id)??0;const totalMinutes=Math.floor(milliseconds/60000);return <tr key={person.id} className="border-b last:border-0"><td className="p-4 font-semibold">{person.full_name}</td><td>{person.role}</td><td>{person.is_active?'Active':'Inactive'}</td><td>{open?duration(open):'Off duty'}</td><td className="p-4 font-bold">{Math.floor(totalMinutes/60)}h {totalMinutes%60}m</td></tr>})}</tbody></table></div></section>
  <section className="mt-6 overflow-x-auto rounded-2xl bg-white shadow-sm"><h2 className="p-4 text-lg font-bold">Attendance history</h2><table className="w-full min-w-[760px] text-left"><thead className="border-y bg-stone-50 text-xs uppercase text-stone-500"><tr><th className="p-4">Staff</th><th>Clock in</th><th>Clock out</th><th>Method</th><th className="p-4">Duty time</th></tr></thead><tbody>{filteredAttendance.map(item=><tr key={item.id} className="border-b last:border-0"><td className="p-4 font-semibold">{item.profiles?.full_name??'Staff'}</td><td>{new Date(item.clocked_in_at).toLocaleString()}</td><td>{item.clocked_out_at?new Date(item.clocked_out_at).toLocaleString():'On duty'}</td><td>{item.login_method==='FACE'?'Face':'Admin recovery'}</td><td className="p-4">{duration(item)}</td></tr>)}{filteredAttendance.length===0&&<tr><td colSpan={5} className="p-10 text-center text-stone-500">No attendance records for this month.</td></tr>}</tbody></table></section></div>
}
